name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR with Maven
        run: |
          chmod +x mvnw
          ./mvnw clean package

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t dhruv1503/verimed:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push dhruv1503/verimed:latest

      - name: Deploy to Render
        run: |
          curl -X POST -d '' ${{ secrets.RENDER_DEPLOY_HOOK }}


